#!/bin/bash
# Wrapper for Emacs daemon that always launches a terminal frame

function launch-emacs()
{
    emacsclient --alternate-editor="" -t "${@}" 2>/dev/null
}

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${DIR}/emacs-daemon-core"
