#!/bin/bash
# Wrapper for Emacs daemon that opens in an existing frame, if possible

function launch-emacs()
{
    if ! emacsclient -n "${@}" 2>/dev/null; then
        if [ -z "${DISPLAY}" ]; then
            emacsclient --alternate-editor="" -t "${@}" 2>/dev/null
        else
            emacsclient -n --alternate-editor="" -c "${@}" 2>/dev/null
        fi
    fi
}

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${DIR}/emacs-daemon-core"
